# Generated by Django 4.0.3 on 2022-06-21 01:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('client', models.CharField(max_length=150, verbose_name='Cliente')),
                ('nit_client', models.CharField(max_length=20, unique=True, verbose_name='NIT')),
                ('address_client', models.CharField(max_length=300, verbose_name='Dirección')),
                ('phone_client', models.CharField(max_length=50, verbose_name='Telefónos')),
                ('mail_client', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('contact_client', models.CharField(max_length=300, verbose_name='Contacto')),
                ('user_creation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_creation', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'db_table': 'Client',
            },
        ),
    ]
